package:
  name: pypackagelib

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - pypackagelib

about:
  home: https://github.com/farrajota/pypackagelib
  license: MIT